### ISSUE TITLE
2 Player pos_list bug

### ISSUE THREAD

**Issue by zacknawrocki** [gibboa/Open_IO#28] opened 2019-04-18 23:37 UTC
<img width="560" alt="Screen Shot 2019-04-18 at 7 35 55 PM" src="https://user-images.githubusercontent.com/40272327/56397329-41d5af80-6211-11e9-81a1-f1e104f5b8bd.png">

**Comment by gibboa** [comment] 2019-04-19 01:06
Can you provide any details on this? This is actually a bug with the .path, there are lots of things that screw with this, I thought we fixed em all, but apparently not

**Comment by gibboa** [comment] 2019-04-19 03:53
I got this recently when eating a food with a length 4 snake, with 2 players on the board after a number of refreshes... peculiar... I lengthened the initial path just in case, but that shouldn't be the cause or solution so we'll have to keep an eye out for this

**Comment by zacknawrocki** [comment] 2019-04-19 03:57
While I currently cannot reproduce the bug, I received it with two snakes on the board (separate tabs), as well, both when the snakes were side by side. Unfortunately, this bug is not easily repeatable like some of the others at the moment, but is still pretty important to look into, since the server crashes, meaning it ruins the game for everyone.

I'll keep looking into this.

**Comment by gibboa** [comment] 2019-04-19 12:45
Ok it miiight be fixed now, my early fix had a mistake (i forgot to increase path_len, so the increase to path was just getting popped off to get back down to the old path_len) it should be fixed, I hanvt been able to recreate it. ill close this for now

**Closed by gibboa** 2019-04-19 12:45 UTC

**Comment by zacknawrocki** [comment] 2019-04-22 20:50
Yes, I think it's all set.
